### Essential NumPy and Pandas Functions for Data Analysis

Let's look at practical code snippets that demonstrate the most useful NumPy and pandas methods for data analysis in Python. You can use these in a Jupyter notebook for experimentation and workflow mastery.

#### NumPy Basics for Data Analysis
Import NumPy:

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

1. Creating Arrays

In [ ]:
arr = np.array([1, 2, 3, 4])            # 1D array
matrix = np.array([[1, 2], [3, 4]])     # 2D array
zeros = np.zeros((2, 3))                # 2x3 array of zeros
ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 3)              # 2x3 array of random floats

2. Array Shape, Reshape, Flatten

In [ ]:
print(arr.shape)                # (4,)
reshaped = matrix.reshape((4, 1))   # Reshape to 4 rows, 1 column
flat = matrix.ravel()               # Flatten to 1D array

(4,)


3. Indexing and Slicing

In [ ]:
print(matrix[0, 1])    # element at first row, second column
print(arr[1:3])        # slice elements 1 to 2

2
[2 3]


4. Basic Math Operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)           # [11 22 33]
print(a - b)           # [ 9 18 27]
print(a * b)           # [10 40 90]
print(a / b)           # [10. 10. 10.]


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5. Aggregation and Stats

In [ ]:
np.sum(arr)                 # 10
np.mean(arr)                # 2.5
np.std(arr)                 # Standard deviation
np.min(arr), np.max(arr)    # Min and max values

(1, 4)

6. Dot Product, Matrix Ops

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

7. Logical and Filtering

In [ ]:
arr[arr > 2]                # Returns [3, 4]
np.where(arr > 2)           # Indices where condition is true

(array([2, 3], dtype=int64),)

8. Random Sampling

In [ ]:
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0, 1], size=10) # 10 random 0s or 1s

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 1])

#### Pandas Basics for Data Analysis
Import pandas:

In [ ]:
import pandas as pd

1. Creating DataFrames

In [ ]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data) # Create DataFrame

2. Inspecting Data

In [ ]:
df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()             # Summary statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

3. Selecting Data

In [ ]:
df['A']                   # Get column A
df.loc[0]                 # Row by label (index 0)
df.iloc[1:3]              # Rows 1-2 by position
df[df['A'] > 1]           # Filter rows where A > 1

A  B
1  2  5
2  3  6

4. Adding/Dropping Columns

In [ ]:
df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B

5. Missing Values & Types

In [ ]:
df.isnull().sum()               # Missing values per column
df.fillna(0)                    # Replace NaNs with 0
df['A'] = df['A'].astype(float) # Change column type

6. Grouping and Aggregation

In [ ]:
grouped = df.groupby('A').sum()   # Sum columns, grouped by values in A
df['A'].value_counts()            # Count unique values in A

A
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

7. Sorting

In [ ]:
df.sort_values('B', ascending=False)  # Sort by column B

A  B  C
2  3.0  6  9
1  2.0  5  7
0  1.0  4  5

8. Reading/Writing Files

In [ ]:
df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

Unnamed: 0  age  salary department  years_experience  is_manager
0           0   56   38392         IT              -0.8           0
1           1   46   60535  Marketing               3.4           1
2           2   32  108603         HR               5.0           1
3           3   25   82256         HR               4.2           1
4           4   38  119135         HR               4.1           1

9. Apply/Map Functions

In [ ]:
df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(3)

A  B  C  A_squared B_label
2  3.0  6  9        9.0    High
0  1.0  4  5        1.0     Low
1  2.0  5  7        4.0     Med

### Task:

- Generated a Synthetic Dataset with columns of `age`, `salary`, `department`, `years_experience`, and `is_manager`.

In [3]:
import pandas as pd
import numpy as np
np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

Q1. View data structure

to view first few rows

In [4]:
df.head()



age  salary department  years_experience  is_manager
0   56   38392         IT              -0.8           0
1   46   60535  Marketing               3.4           1
2   32  108603         HR               5.0           1
3   25   82256         HR               4.2           1
4   38  119135         HR               4.1           1

To view number of rows and columns in dataset

In [5]:
df.shape

(100, 5)

To view columns of dataset

In [6]:
df.columns

Index(['age', 'salary', 'department', 'years_experience', 'is_manager'], dtype='object')

Q2. Get DataFrame Info and Summary Stats

Dataframe info

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               100 non-null    int64  
 1   salary            100 non-null    int64  
 2   department        100 non-null    object 
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB


Summary statistics (numeric columns)

In [8]:
df.describe()

age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823000    0.470000
std     12.219454   26058.643576          2.237822    0.501614
min     18.000000   30206.000000         -0.800000    0.000000
25%     26.750000   55141.000000          3.475000    0.000000
50%     38.000000   80932.000000          4.700000    0.000000
75%     46.250000   98107.250000          6.000000    1.000000
max     59.000000  119474.000000         11.400000    1.000000

Summary statistics including categorical

In [9]:
df.describe(include='all')

age         salary department  years_experience  is_manager
count   100.000000     100.000000        100        100.000000  100.000000
unique         NaN            NaN          4               NaN         NaN
top            NaN            NaN  Marketing               NaN         NaN
freq           NaN            NaN         36               NaN         NaN
mean     37.910000   77809.160000        NaN          4.823000    0.470000
std      12.219454   26058.643576        NaN          2.237822    0.501614
min      18.000000   30206.000000        NaN         -0.800000    0.000000
25%      26.750000   55141.000000        NaN          3.475000    0.000000
50%      38.000000   80932.000000        NaN          4.700000    0.000000
75%      46.250000   98107.250000        NaN          6.000000    1.000000
max      59.000000  119474.000000        NaN         11.400000    1.000000

Q3. Do Simple Numpy Operations

Standard deviation of years_experience

In [11]:
np.std(df['years_experience'])

2.2266052636244265

maximum salary

In [12]:
np.max(df['salary'])

119474

Q4. Filtering and Indexing Rows

Employees older than 40

In [13]:
df[df['age'] > 40]

age  salary department  years_experience  is_manager
0    56   38392         IT              -0.8           0
1    46   60535  Marketing               3.4           1
5    56   65222    Finance               2.8           0
10   41   40965         IT               9.5           1
11   53   54538  Marketing               5.3           0
12   57  100592    Finance               6.1           1
13   41   38110         HR               2.0           1
17   41  112948  Marketing               6.7           1
18   47   36910  Marketing               7.6           0
19   55   30206    Finance               2.3           0
22   50   53419         HR               5.0           0
25   42   84268    Finance               5.8           0
26   44  117939  Marketing               1.4           0
27   59   48141  Marketing               4.5           0
28   45  110356    Finance               5.7           1
32   54   63827  Marketing               9.2           0
36   56  105450  Marketing               4.8           1
39   42   94044  Marketing               1.8           0
42   43   32693         HR               3.3           0
45   45   78925         HR               4.1           1
48   52   48047    Finance               1.4           1
51   53   45707         HR               4.0           1
52   57   51976  Marketing               3.5           0
56   59   96842         IT               1.9           1
58   46   36776         IT               2.6           1
60   43   39474         HR               5.3           0
61   51   88053  Marketing               5.3           0
63   53   35530         IT               1.2           1
65   48   43545    Finance               4.0           0
70   57   98840    Finance               3.5           0
74   41   69353  Marketing               3.3           0
75   43   92003  Marketing               6.7           0
76   42  113211         HR               8.6           0
77   58   82733  Marketing               3.6           1
78   46   95318         IT               1.9           1
81   42   97172    Finance               6.2           0
84   41   30854  Marketing               8.3           0
87   41   85680  Marketing               3.8           0
91   52   56309         HR               3.8           0
92   52  117455         IT               3.9           0
93   50   93734    Finance               7.2           0
95   59   82662         IT               4.0           0
96   56   42688         HR               4.4           1
97   58   55342  Marketing               6.0           0
98   45   67157         HR              11.4           0

Filters only managers

In [14]:
df[df['is_manager'] == 1]

age  salary department  years_experience  is_manager
1    46   60535  Marketing               3.4           1
2    32  108603         HR               5.0           1
3    25   82256         HR               4.2           1
4    38  119135         HR               4.1           1
6    36  107373    Finance               6.7           1
8    28  114651  Marketing               5.8           1
9    28   93335         IT               1.2           1
10   41   40965         IT               9.5           1
12   57  100592    Finance               6.1           1
13   41   38110         HR               2.0           1
14   20  109309  Marketing               5.0           1
15   39   57266         IT               5.8           1
17   41  112948  Marketing               6.7           1
24   39   80015    Finance               8.0           1
28   45  110356    Finance               5.7           1
29   33  101910  Marketing               6.0           1
31   20   97214         IT               5.7           1
34   38   92623    Finance               3.1           1
36   56  105450  Marketing               4.8           1
37   35   52299         IT               1.5           1
40   31   72557         IT               2.7           1
44   37   55939    Finance               6.8           1
45   45   78925         HR               4.1           1
47   25   51834    Finance               3.5           1
48   52   48047    Finance               1.4           1
49   31   56105  Marketing               5.9           1
50   34  105766  Marketing               1.9           1
51   53   45707         HR               4.0           1
55   23   60080  Marketing               4.7           1
56   59   96842         IT               1.9           1
58   46   36776         IT               2.6           1
62   27   51959         IT               5.7           1
63   53   35530         IT               1.2           1
68   31  103530         IT               4.3           1
69   40   91087    Finance               2.4           1
72   33   81005  Marketing               2.4           1
73   35   76576    Finance               1.0           1
77   58   82733  Marketing               3.6           1
78   46   95318         IT               1.9           1
79   32  119474  Marketing               4.3           1
82   24  115616         IT               9.3           1
83   26   56736  Marketing               5.5           1
85   18   68623         HR               4.1           1
86   25   37392  Marketing               5.2           1
88   28   76717         HR               3.6           1
96   56   42688         HR               4.4           1
99   24   97863         HR               5.2           1

Adding a column for salary category

Q5. Adding a Column

In [15]:
df['salary_level'] = np.where(df['salary'] > 70000, 'High', 'Low')

In [16]:
df.head()

age  salary department  years_experience  is_manager salary_level
0   56   38392         IT              -0.8           0          Low
1   46   60535  Marketing               3.4           1          Low
2   32  108603         HR               5.0           1         High
3   25   82256         HR               4.2           1         High
4   38  119135         HR               4.1           1         High

Q6. Grouping and Aggregation

Average salary per department

In [17]:
df.groupby('department')['salary'].mean()

department
Finance      83124.708333
HR           73523.052632
IT           75825.476190
Marketing    77684.722222
Name: salary, dtype: float64

Count employees per department

In [18]:
df.groupby('department').size()

department
Finance      24
HR           19
IT           21
Marketing    36
dtype: int64