In [29]:
#NUMPY
import numpy as np
arr = np.array([1, 2, 3, 4])            # 1D array
matrix = np.array([[1, 2], [3, 4]])     # 2D array
zeros = np.zeros((2, 3))                # 2x3 array of zeros
ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 3)              # 2x3 array of random floats
print(rnd)

[[0.49656119 0.38961809 0.29763517]
 [0.09998489 0.0534853  0.9585415 ]]


In [ ]:

print(arr.shape)
reshape =  matrix.reshape((4,1))
flat = matrix.ravel()

print(matrix[0, 1]) # element at first row, second column
print(arr[1:3]) # slice elements 1 to 2

a = np.array([10, 20, 30])
b = np.array([1,2,3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)


(4,)
2
[2 3]
[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [ ]:
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

arr[arr > 2] # Return [3, 4]
np.where(arr > 2) # Indices where condition is true
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0,1], size=10)  # 10 random 0s  or 1s

10
2.5
1.118033988749895
1
4


array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
#PANDAS

In [ ]:

import pandas as pd

data = {'A':[1,2,3], 'B':[4,5,6]}
df = pd.DataFrame(data) # Create DataFrame
df.head()

df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()

df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B
new_df

df['A'] = df['A'].astype(float) # Change column type
df.info()

grouped = df.groupby('A').sum() # Sum columns, grouped by values in A
df['A'].value_counts()

df.sort_values('B', ascending=False)

df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       3 non-null      float64
 1   B       3 non-null      int64  
 2   C       3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 204.0 bytes


Unnamed: 0    A  B  C
0           0  1.0  4  5
1           1  2.0  5  7
2           2  3.0  6  9

In [ ]:

df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(3)

Unnamed: 0    A  B  C  A_squared B_label
1           1  2.0  5  7        4.0     Med
0           0  1.0  4  5        1.0     Low
2           2  3.0  6  9        9.0    High

In [ ]:
#TASK
np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

In [ ]:
#Q1. View data structure
print(df.shape)             # rows, cols [web:3]
print(df.columns.tolist())  # column names [web:3]
print(df.dtypes)            # dtypes [web:3]
display(df.head())          # first rows [web:3]


(100, 5)
['age', 'salary', 'department', 'years_experience', 'is_manager']
age                   int64
salary                int64
department           object
years_experience    float64
is_manager            int64
dtype: object


age  salary department  years_experience  is_manager
0   56   38392         IT              -0.8           0
1   46   60535  Marketing               3.4           1
2   32  108603         HR               5.0           1
3   25   82256         HR               4.2           1
4   38  119135         HR               4.1           1

In [ ]:
#Q2. Get DataFrame info and summary stats
df.info()  # concise schema summary [web:3]

# numeric summary
display(df.describe())

# categorical/binary summaries
display(df['department'].value_counts())  # frequency by department [web:3]
display(df['is_manager'].value_counts())  # manager vs non-manager counts [web:3]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               100 non-null    int64  
 1   salary            100 non-null    int64  
 2   department        100 non-null    object 
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB


age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823000    0.470000
std     12.219454   26058.643576          2.237822    0.501614
min     18.000000   30206.000000         -0.800000    0.000000
25%     26.750000   55141.000000          3.475000    0.000000
50%     38.000000   80932.000000          4.700000    0.000000
75%     46.250000   98107.250000          6.000000    1.000000
max     59.000000  119474.000000         11.400000    1.000000

department
Marketing    36
Finance      24
IT           21
HR           19
Name: count, dtype: int64

is_manager
0    53
1    47
Name: count, dtype: int64

In [ ]:
#Q3. Do simple NumPy operations
arr_salary = df['salary'].to_numpy()  # vector view [web:3]
salary_mean = np.mean(arr_salary)
salary_std  = np.std(arr_salary, ddof=1)

# z-score normalization
salary_z = (arr_salary - salary_mean) / salary_std

print("Mean salary:", salary_mean)
print("Sample std salary:", salary_std)
print("First 5 z-scores:", salary_z[:5])

# vectorized numeric feature: experience to salary ratio (per 1k)
ratio = df['years_experience'].to_numpy() / (arr_salary / 1000.0)
print("First 5 exp/salary(1k):", ratio[:5])


Mean salary: 77809.16
Sample std salary: 26058.64357568222
First 5 z-scores: [-1.51263284 -0.66289559  1.18171308  0.17064741  1.5858784 ]
First 5 exp/salary(1k): [-0.02083767  0.05616585  0.04603924  0.05106011  0.03441474]


In [ ]:
#Q4. Filtering and indexing rows
# example filters
mask = (
    (df['department'].isin(['IT', 'Finance'])) &  # department filter [web:3]
    (df['salary'] > 80000) &                      # salary threshold [web:3]
    (df['years_experience'] >= 5)                 # experience threshold [web:3]
)
filtered = df.loc[mask, ['age','salary','department','years_experience','is_manager']]  # label indexing [web:3]
display(filtered.head())  # preview [web:3]

# positional indexing example
display(df.iloc[:5, :3])  # first 5 rows, first 3 columns [web:3]

# compound condition and sorted view
subset = df.loc[(df['is_manager']==1) & (df['salary']>=90000), ['department','salary','years_experience']]  # [web:3]
display(subset.sort_values('salary', ascending=False).head())  # [web:3]



age  salary department  years_experience  is_manager
6    36  107373    Finance               6.7           1
12   57  100592    Finance               6.1           1
21   38  117897    Finance               5.8           0
24   39   80015    Finance               8.0           1
25   42   84268    Finance               5.8           0

age  salary department
0   56   38392         IT
1   46   60535  Marketing
2   32  108603         HR
3   25   82256         HR
4   38  119135         HR

department  salary  years_experience
79  Marketing  119474               4.3
4          HR  119135               4.1
82         IT  115616               9.3
8   Marketing  114651               5.8
17  Marketing  112948               6.7

In [ ]:
#Q5. Adding a column
df = df.copy()  # safe copy before mutation [web:3]

# derived features
df['salary_k'] = (df['salary'] / 1000.0).round(1)  # salary in thousands [web:3]
df['exp_per_year_pay_k'] = (df['years_experience'] / df['salary_k']).round(3)  # experience per 1k pay [web:3]
df['senior_flag'] = (df['years_experience'] >= 7).astype(int)  # binary flag [web:3]

display(df.head())  # confirm new columns [web:3]


age  salary department  years_experience  is_manager  salary_k  \
0   56   38392         IT              -0.8           0      38.4   
1   46   60535  Marketing               3.4           1      60.5   
2   32  108603         HR               5.0           1     108.6   
3   25   82256         HR               4.2           1      82.3   
4   38  119135         HR               4.1           1     119.1   

   exp_per_year_pay_k  senior_flag  
0              -0.021            0  
1               0.056            0  
2               0.046            0  
3               0.051            0  
4               0.034            0

In [ ]:
#Q6. Grouping and aggregation
# group by department with multiple aggregations
agg_dept = (
    df.groupby('department', observed=True)  # only show observed categories if categorical [web:3][web:2]
      .agg(
          avg_age=('age','mean'),
          avg_salary=('salary','mean'),
          median_exp=('years_experience','median'),
          managers=('is_manager','sum'),
          count=('age','count')
      )
      .round(2)
)
display(agg_dept)  # grouped stats per department [web:3][web:2]

# group by department and manager status
agg_dept_mgr = (
    df.groupby(['department','is_manager'], observed=True)
      .agg(
          avg_salary=('salary','mean'),
          n=('salary','count')
      )
      .round(2)
)
display(agg_dept_mgr)  # split-apply-combine result [web:5][web:3]

# pivot table for quick comparison
pivot = pd.pivot_table(
    df,
    values='salary',
    index='department',
    columns='is_manager',
    aggfunc='mean'
).round(2)  # mean salary by dept x manager [web:3]
display(pivot)


avg_age  avg_salary  median_exp  managers  count
department                                                  
Finance       39.42    83124.71        4.25        10     24
HR            37.16    73523.05        4.20        10     19
IT            36.81    75825.48        4.30        13     21
Marketing     37.94    77684.72        5.30        14     36

avg_salary   n
department is_manager                
Finance    0             84325.07  14
           1             81444.20  10
HR         0             70923.44   9
           1             75862.70  10
IT         0             80391.00   8
           1             73015.92  13
Marketing  0             72388.91  22
           1             86006.71  14

is_manager         0         1
department                    
Finance     84325.07  81444.20
HR          70923.44  75862.70
IT          80391.00  73015.92
Marketing   72388.91  86006.71